---
services:
  generative_agents:
    container_name: generative_agents
    image: jh1950/generative-agents-docker:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Seoul"
      PUID: 1000
      PGID: 1000
      SYNC_TZ: true
      ALLOWED_HOSTS: "*"
      CUSTOM_UTILS: false  # Manually create data/BACKEND_ROOT/utils.py if true
      OPENAI_API_KEY: "OpenAI-API-KEY"  # Use if CUSTOM_UTILS is false
      OPENAI_API_OWNER: "OpenAI-API-OWNER"  # Use if CUSTOM_UTILS is false
    volumes:
      - ./data:/data
